[package]
name = "my-app-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name="my-app-rust"
path="src/variable-not.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

